network:
  hardhat:
    contracts:
      - name: 'DexCalc'
        address: '0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512'
      - name: 'Factory'
        address: '0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0'
        eventList:
          - 'PairCreated'
      - name: 'WETH'
        address: '0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9'
      - name: 'Router'
        address: '0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9'
      - name: 'tokenA'
        address: '0x5FC8d32690cc91D4c39d9d3abcBD16989F875707'
      - name: 'tokenB'
        address: '0x0165878A594ca255338adfa4d48449f69242Eb8F'
      - name: 'tokenC'
        address: '0xa513E6E4b8f2a923D98304ec87F64353C4D5C853'
      - name: 'Pair'
        address:
        eventList:
          - 'Sync'
          - 'Mint'
          - 'Burn'
          - 'Swap'

  sepolia:
    contracts:
      - name: 'DexCalc'
        address:
      - name: 'Factory'
        address:
        eventList:
          - 'PairCreated'
      - name: 'WETH'
        address:
      - name: 'Router'
        address:
      - name: 'tokenA'
        address:
      - name: 'tokenB'
        address:
      - name: 'tokenC'
        address:
      - name: 'Pair'
        address:
        eventList:
          - 'Sync'
          - 'Mint'
          - 'Burn'
          - 'Swap'

  mumbai:
    contracts:
      - name: 'DexCalc'
        address:
      - name: 'Factory'
        address:
        eventList:
          - 'PairCreated'
      - name: 'WETH'
        address:
      - name: 'Router'
        address:
      - name: 'tokenA'
        address:
      - name: 'tokenB'
        address:
      - name: 'tokenC'
        address:
      - name: 'Pair'
        address:
        eventList:
          - 'Sync'
          - 'Mint'
          - 'Burn'
          - 'Swap'

contracts:
  - name: 'DexCalc'
    address:
  - name: 'Factory'
    address:
    eventList:
      - 'PairCreated'
  - name: 'WETH'
    address:
  - name: 'Router'
    address:
  - name: 'tokenA'
    address:
  - name: 'tokenB'
    address:
  - name: 'tokenC'
    address:
  - name: 'Pair'
    address:
    eventList:
      - 'Sync'
      - 'Mint'
      - 'Burn'
      - 'Swap'
